### ISSUE TITLE
Footer not appearing in <footer>

### ISSUE THREAD

**Issue by jimt** [oeru/wordpress-oeru_theme#45]
The attribution, copyright notice/logo, and institution logo is not appearing in the (dark grey by default) footer section, but in a lighter grey section between the content area and the footer. It should either be moved to the footer, or the empty dark grey footer block removed.

![image](https://user-images.githubusercontent.com/180326/37011452-9a4cc592-2133-11e8-82fa-9e30101bf5c6.png)

**Comment by lightweight** [comment]
Thanks for this, Jim. I'll sort it out asap.

**Comment by lightweight** [comment]
Ok, fixed, removed the darker section below, added some spacing around the logo to keep it from being too close to the main frame.
